version: "3"
services:
  db:
    image: postgres:15
    container_name: arabica-postgres
    environment:
      POSTGRES_DB: arabica_db
      POSTGRES_USER: arabica_user
      POSTGRES_PASSWORD: arabica
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7
    container_name: arabica-redis
    ports:
      - "6379:6379"
    restart: always

  django:
    build: .
    container_name: arabica-back
    working_dir: /src
    environment:
      - DJANGO_ENV=production
    volumes:
      - .:/src
      - static_volume:/static
      - media_volume:/media
    restart: always
    depends_on:
      - db
      - redis
    command: sh -c "python manage.py migrate && gunicorn arabica.wsgi:application --bind 0.0.0.0:8000"

  nginx:
    image: nginx
    container_name: arabica-nginx
    ports:
      - "8001:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/static
      - media_volume:/media
    depends_on:
      - django

volumes:
  static_volume:
  media_volume:
  postgres_data:
